### ISSUE TITLE
[BUG]: TypeError: _h.toText is not a function

### ISSUE THREAD

**Issue by nescafe2002** [naimo84/kalender-events#15]
**Describe the bug**
Parsing iCal with recurring events throws an exception dependent on the preview window.

**To Reproduce**
Setup environment:
- docker run --rm -it -e TZ=Europe/Amsterdam alpine
- apk add npm
- npm install -g kalender-events-cli

**ICS file**
The file is available here: https://gist.githubusercontent.com/nescafe2002/3ff4deb74fb2befff244510586165b9b/raw/8b183aa08a1b559cc708786fc7fc4e543946850f/calendar.ics

```
BEGIN:VCALENDAR
METHOD:PUBLISH
VERSION:2.0
BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20240606T070000Z;INTERVAL=1;BYDAY=MO,TH;WKST=MO
UID:1234
RECURRENCE-ID;TZID=W. Europe Standard Time:20220103T090000
SUMMARY:Test
DTSTART;TZID=W. Europe Standard Time:20220609T090000
DTEND;TZID=W. Europe Standard Time:20220609T133000
END:VEVENT
END:VCALENDAR
```

```
/ # kalender-events --preview P1D --url https://gist.githubusercontent.com/nescafe2002/3ff4deb74fb2befff244510586165b9b/raw/8b183aa08a1b559cc708786fc7fc4e543946850f/calendar.ics
TypeError: _h.toText is not a function
    at convertEvent (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/convert.js:99:83)
    at KalenderEvents.processRRule (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/lib.js:324:58)
    at KalenderEvents.processDataRev (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/lib.js:357:39)
    at KalenderEvents.processData (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/lib.js:337:14)
    at KalenderEvents.<anonymous> (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/lib.js:139:42)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/kalender-events-cli/node_modules/kalender-events/dist/lib.js:24:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**
For comparison, the correct output appears when using a larger preview window:

```
/ # kalender-events --preview P3D --url https://gist.githubusercontent.com/nescafe2002/3ff4deb74fb2befff244510586165b9b/raw/8b183aa08a1b559cc708786fc7fc4e543946850f/calendar.ics
[
  {
    date: '6/12/2023',
    eventStart: 2023-06-12T07:00:00.000Z,
    eventEnd: 2023-06-12T11:30:00.000Z,
    summary: 'Test',
    duration: 'PT4H30M',
    durationSeconds: 16200,
    rrule: { _cache: [Object], origOptions: [Object], options: [Object] },
    rruleText: 'every week on Monday, Thursday until June 6, 2024 (~ approximate)',
    uid: { uid: '1234', date: '1654758000000' },
    isRecurring: true,
    datetype: 'date',
    allDay: false,
    calendarName: null
  }
]
```

**Additional context**
The error occurs in the following line:

https://github.com/naimo84/kalender-events/blob/3c4d0f6e4f890e256145a32c9e5b29152b938db9/src/convert.ts#L117

Note that the issue started occuring on a friday (June 9th 2023) after midnight, so it is actually dependent on the current date or day of week:

- Monday - working
- Tuesday - unknown*
- Wednesday - unknown*
- Thursday - working
- Friday - not working
- Saturday - not working
- Sunday - unknown*

It seems non reproducible on the days the appointment is recurring (monday and thurday)

(*) requires further testing

**Comment by naimo84** [comment]
Should be fixed with the latest version 👍 
If not, feel free to comment or reopen it 😉
